### ISSUE TITLE
The question about hyperparameter in the search function in the agmc_network_pruning.py file

### ISSUE THREAD

**Issue by MingGuo-alt** [yusx-swapp/AGMC#1]
Hello! 
I have read your article before and want to know more about it.
I have some questions to consult you, if you can reply will be very appreciated!
Is this formal code base? How to set the hyperparameter in the search function in the agmc_network_pruning.py file?
Thank you very much!

**Comment by yusx-swapp** [comment]
Sorry for my late! 
Thank you for your interest, if you are working on network pruning or model compression, we improved the AGMC it been merged into our new method GNN-RL, and you can find it here:
https://github.com/yusx-swapp/GNN-RL-Model-Compression/

The AGMC is no longer maintained.
