### ISSUE TITLE
Incomplete Source Code for Paper Replication

### ISSUE THREAD

**Issue by a-cup-of-joe** [yusx-swapp/AGMC#2]
Dear Author/Contributor,

I hope this message finds you well. I am currently working on replicating the results of your paper titled "AGMC" and I am using the source code you kindly provided on this repository.

However, I've noticed that some key parts of the implementation seem to be missing from the repository, making it difficult to fully replicate your work.

Could you kindly provide the missing parts of the source code, or guide me on how the missing functionality can be implemented? Especially how the LSTM decoder works and how to implemente the RL agent. Your assistance would be of great help to my research.

Thank you in advance for your cooperation and for your contributions to the scientific community.

**Comment by yusx-swapp** [comment]
Thank you for your interest, if you are working on network pruning or model compression, we improved the AGMC it been merged into our new method GNN-RL, and you can find it here:
https://github.com/yusx-swapp/GNN-RL-Model-Compression/

The AGMC is no longer maintained.
